upower_battery_path = "/org/freedesktop/UPower/devices/battery_BAT0"
on_battery = "powersave"
on_wallpower = "performance"

[presets.powersave]
epp = "power"
hwp_dynamic_boost = false
no_turbo = true
scaling_governor = "powersave"

[presets.balanced]
epp = "default"
hwp_dynamic_boost = false
no_turbo = true
scaling_governor = "powersave"

[presets.performance]
hwp_dynamic_boost = true
no_turbo = false
scaling_governor = "performance"
